---
 - name: Install node dependencies
   shell: |
    # 1. Add the PM2 repository signing key
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv D1EA2D4C

    # 2. Add the PM2 repository
    echo "deb http://apt.pm2.io/ubuntu stable main" | sudo tee /etc/apt/sources.list.d/pm2.list

    # 3. Update list of available packages
    sudo apt-get update

    # 4. Install nodejs
    sudo apt-get install nodejs

    # 5. Install PM2
    sudo apt-get install pm2

 - name: Set-up env variables
   environment:
    ENVIRONMENT: Production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udacityproject.c5cjhltyuv22.eu-west-1.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: postgres
    TYPEORM_DATABASE: udacityproject