---
- name: "Update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "Upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "Add nodejs apt key"
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: "Add nodejs 14.x ppa for apt repo"
  become: yes
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo bash -
    sudo apt-get install nodejs

- name: Install dependencies
  become: yes
  apt:
    name: ["npm", "tar"]
    state: latest
    update_cache: yes

- name: Create soft link for node 
  become: yes
  shell: ln -s /usr/bin/nodejs /usr/bin/node

- name: Install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
  