---
- name: "Update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "Upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: Install dependencies
  become: yes
  apt:
    name: ["nodejs", "npm", "tar"]
    state: latest
    update_cache: yes

- name: Set-up env variables and install pm2
  environment:
    ENVIRONMENT: Production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udapeople.c5cjhltyuv22.eu-west-1.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: udapeople
    TYPEORM_DATABASE: postgres
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
  