---
 - name: copy files
   copy: 
    src: backend.tar.gz
    dest: .
 - name: "use pm2 to runserver"
   shell: |
     tar -xzf backend.tar.gz

 - name: "use pm2 to runserver"
   shell: |
     cd backend
     