---
 - name: copy files
   copy: 
    src: backend.tar.gz
    dest: .

 - name: "Update node to 13.X"
   shell: |
     curl -sL https://deb.nodesource.com/setup_13.x | sudo bash -
     sudo apt-get install nodejs -y

 - name: "use pm2 to runserver"
   shell: |
     tar -xzf backend.tar.gz

 - name: "use pm2 to runserver"
   shell: |
     cd backend
     pm2 start npm --name backend -- start