version: 2.1

jobs:
  create_infra:
    docker:
      - image: amazon/aws-cli # every job must define an image for the docker executor and subsequent jobs may define a different image.
    steps:
      - checkout
      - run: >
         aws cloudformation deploy \
              --template-file template.yml \
              --stack-name udacity-cd-infra
      - run:
          name: Check fail
          command: |
            aws cloudformation describe-stack-events --stack-name udacity-cd-infra
            echo "DONE"
          when: always
workflows:
  main:
    jobs:   
      - create_infra
