version: 2.1

jobs:
  create_infra:
    docker:
      - image: circleci/python:3.6.1 # every job must define an image for the docker executor and subsequent jobs may define a different image.
    steps:
      - add_ssh_keys:
          fingerprints: 
            - "65:25:32:d2:c6:d1:d5:3f:a0:b1:2c:77:e2:d3:0f:bb" 
      - checkout
      # - run: sudo apt-get install ansible 
      # - run: |
      #     export ANSIBLE_HOST_KEY_CHECKING=False
      #     ansible-playbook ansible/main.yml -i ansible/inventory.txt
      - run: sudo apt-get install curl
      - run: curl www.alsñkdfj.com
      - run: 
          name: catch error
          command: |
            echo failed
            return 1
          when: on_fail
      

workflows:
  main:
    jobs:   
      - create_infra
