version: 2.1

jobs:
  create_infra:
    docker:
      - image: amazon/aws-cli # every job must define an image for the docker executor and subsequent jobs may define a different image.
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: >
          aws cloudformation create-stack 
          --stack-name udacity-cd-infra-creation 
          --template-url https://s3-eu-west-1.amazonaws.com/cf-templates-146g4lxm0y808-eu-west-1/20210270J2-template.yml
          --role-arn arn:aws:iam::563631770844:role/udacity-cloudformation
workflows:
  main:
    jobs:
      - create_infra
