---
 - name: Print env variable
   shell: echo $PATH
   register: print_result

 - name: print message
   debug:
     msg: "{{ print_result.stdout_lines }}"

 - name: shell command
   shell: |
     pwd 
     mkdir test
     touch test/test.txt
     echo "asdas" >> test/test.txt
     exit 0
